<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto

namespace Waterandair\AuthGrpc\GPBMetadata;

class Auth
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa5010a0a617574682e70726f746f12147761746572616e646169722e61" .
            "7574684772706322070a05456d70747922180a08526573706f6e7365120c" .
            "0a04696e666f18012001280932500a044175746812480a07476574496e66" .
            "6f121b2e7761746572616e646169722e61757468477270632e456d707479" .
            "1a1e2e7761746572616e646169722e61757468477270632e526573706f6e" .
            "7365220042045a027062620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

